export default {
  CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
  SET_NUMBER_OF_USERS: 'SET_NUMBER_OF_USERS',
  USERS_ARRAY: 'USERS_ARRAY',
  SET_SELECTED_USER: 'SET_SELECTED_USER',
  SET_MESSAGES:"SET_MESSAGES"
};
